language: php

php:
  - 5.5
  - 5.6

install:
  - travis_retry composer install --no-interaction --prefer-dist

notifications:
  email:
    recipients:
      - cs686@126.com
    on_success: always
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text